useServer: true
port: 3000
html:
  lang: "pt-BR"
  head:
    title: "Minha Aplicação"
    meta:
      - charset: "UTF-8"
      - name: "viewport"
        content: "width=device-width, initial-scale=1.0"
  links:
    - rel: "stylesheet"
      href: "styles/global.css"
  scripts:
    - src: "scripts/global.js"
pages:
  home: "src/pages/home-page.ts"